
name: rickroll
on: [push]
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: potential rickroll
        run: echo you have succesfully pushed! run this link for reward! https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley

     
 
 
 

      
